(() => {
  const state = { inbox: [], drafts: [], selected: null, view: 'inbox', loading: false, notice: '', error: '' };
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const sender = message => message?.from?.emailAddress?.name || message?.from?.emailAddress?.address || 'Expéditeur inconnu';
  const senderEmail = message => message?.from?.emailAddress?.address || '';
  const dateLabel = value => { const d = new Date(value || ''); return Number.isNaN(d.getTime()) ? '' : new Intl.DateTimeFormat('fr-CA', { day:'numeric', month:'short', hour:'2-digit', minute:'2-digit', timeZone:'America/Toronto' }).format(d); };
  const root = () => document.querySelector('[data-mailbox-root]');
  const processed = () => { try { return JSON.parse(localStorage.getItem('gc-outlook-drafts') || '[]'); } catch { return []; } };
  const saveProcessed = ids => localStorage.setItem('gc-outlook-drafts', JSON.stringify(ids.slice(-100)));
  const graph = (path, options) => window.M365.graph(path, options);
  const draftQuery = '/me/mailFolders/drafts/messages?$top=25&$orderby=lastModifiedDateTime%20desc&$select=id,subject,toRecipients,lastModifiedDateTime,bodyPreview';
  const inboxQuery = '/me/mailFolders/inbox/messages?$top=25&$orderby=receivedDateTime%20desc&$select=id,subject,from,receivedDateTime,isRead,bodyPreview,webLink';

  function shell() { return `<section class="outlook-panel" data-mailbox-root><div class="outlook-header"><div><p class="eyebrow">MICROSOFT OUTLOOK · MAISONNORD</p><h2>Boîte courriel connectée</h2><span>Lecture, réponses et brouillons synchronisés avec Outlook.</span></div><div class="outlook-status"><i></i><strong>Outlook connecté</strong><button class="button button-outline" type="button" data-mail="refresh">Actualiser</button></div></div><div class="auto-draft-control" role="status"><span class="auto-draft-icon">✦</span><div><strong>Brouillons automatiques actifs</strong><p>Analysez les nouveaux messages et préparez des réponses dans Outlook sans aucun envoi direct.</p></div><button class="button button-outline" type="button" data-mail="analyze">Analyser maintenant</button></div><nav class="mail-tabs" aria-label="Sections Outlook"><button type="button" data-mail="tab" data-view="inbox">Boîte de réception <b data-count="inbox">0</b></button><button type="button" data-mail="tab" data-view="drafts">Brouillons Outlook <b data-count="drafts">0</b></button><button type="button" data-mail="tab" data-view="new">+ Nouveau brouillon</button></nav><div class="outlook-feedback" data-mail-feedback hidden></div><div data-mail-content></div></section>`; }
  function inboxHtml() { const selected = state.selected || state.inbox[0]; return `<div class="mailbox-layout"><div class="mail-list" aria-label="Courriels reçus">${state.loading && !state.inbox.length ? '<div class="mail-loading">Chargement de la boîte de réception…</div>' : ''}${!state.loading && !state.inbox.length ? '<div class="mail-loading">Aucun courriel dans la boîte de réception.</div>' : ''}${state.inbox.map(m => `<button type="button" class="${selected?.id === m.id ? 'active ' : ''}${m.isRead ? '' : 'unread'}" data-mail="open" data-id="${esc(m.id)}"><span><strong>${esc(sender(m))}</strong><small>${esc(dateLabel(m.receivedDateTime))}</small></span><b>${esc(m.subject || '(Sans sujet)')}</b><p>${esc(m.bodyPreview || 'Aucun aperçu disponible.')}</p></button>`).join('')}</div><div class="mail-reader">${selected ? readerHtml(selected) : '<div class="mail-loading">Sélectionnez un courriel.</div>'}</div></div>`; }
  function readerHtml(m) { return `<div class="mail-reader-heading"><div><small>DE ${esc(sender(m))}</small><h3>${esc(m.subject || '(Sans sujet)')}</h3><span>${esc(dateLabel(m.receivedDateTime))}</span></div>${m.webLink ? `<a href="${esc(m.webLink)}" target="_blank" rel="noreferrer">Ouvrir dans Outlook ↗</a>` : ''}</div><p class="mail-preview">${esc(m.bodyPreview || 'Aucun aperçu disponible.')}</p><form class="reply-form" data-mail="reply"><label>Préparer une réponse<textarea name="reply" rows="6" placeholder="Écrivez votre réponse; elle sera créée dans les brouillons Outlook…" required></textarea></label><div><small>La réponse est créée dans Outlook. Aucun message n’est envoyé.</small><button class="button button-primary" type="submit">Créer le brouillon de réponse</button></div></form>`; }
  function draftsHtml() { return `<div class="outlook-drafts">${state.loading && !state.drafts.length ? '<div class="mail-loading">Chargement des brouillons…</div>' : ''}${!state.loading && !state.drafts.length ? '<div class="mail-loading">Aucun brouillon Outlook.</div>' : ''}${state.drafts.map(d => `<article><span class="draft-channel">✉</span><div><small>À ${(d.toRecipients || []).map(r => esc(r.emailAddress?.address)).join(', ') || 'destinataire à confirmer'}</small><h3>${esc(d.subject || '(Sans sujet)')}</h3><p>${esc(d.bodyPreview || 'Brouillon vide')}</p></div><aside><small>${esc(dateLabel(d.lastModifiedDateTime))}</small></aside></article>`).join('')}</div>`; }
  function newHtml() { return `<form class="outlook-compose" data-mail="new"><div><p class="eyebrow">NOUVEAU COURRIEL</p><h3>Créer directement dans les brouillons Outlook</h3></div><label>Destinataire<input name="to" type="email" required placeholder="client@exemple.ca"></label><label>Sujet<input name="subject" placeholder="Suivi de votre dossier"></label><label>Message<textarea name="body" rows="9" required placeholder="Écrivez le courriel à faire vérifier…"></textarea></label><div class="composer-note"><span>i</span><p>Le bouton crée un brouillon dans Outlook. Il ne peut pas envoyer le message.</p></div><button class="button button-primary" type="submit">Créer dans Outlook</button></form>`; }
  function renderContent() { const r = root(); if (!r) return; r.querySelector('[data-mail-content]').innerHTML = state.view === 'inbox' ? inboxHtml() : state.view === 'drafts' ? draftsHtml() : newHtml(); r.querySelectorAll('[data-mail="tab"]').forEach(b => b.classList.toggle('active', b.dataset.view === state.view)); r.querySelector('[data-count="inbox"]').textContent = state.inbox.length; r.querySelector('[data-count="drafts"]').textContent = state.drafts.length; }
  function feedback(text, error = false) { const b = root()?.querySelector('[data-mail-feedback]'); if (!b) return; b.hidden = !text; b.className = `outlook-feedback ${error ? 'outlook-error' : 'outlook-success'}`; b.innerHTML = `<span>${error ? '!' : '✓'}</span><p>${esc(text)}</p>`; }
  async function loadMailbox() { const r = root(); if (!r || state.loading) return; state.loading = true; state.error = ''; renderContent(); try { const [inbox, drafts] = await Promise.all([graph(inboxQuery), graph(draftQuery)]); state.inbox = inbox.value || []; state.drafts = drafts.value || []; state.selected = state.inbox[0] || null; renderContent(); feedback(`${state.inbox.length} courriels et ${state.drafts.length} brouillons Outlook chargés.`); } catch (e) { feedback(e.message || 'Impossible de lire Outlook.', true); } finally { state.loading = false; renderContent(); } }
  const replyText = message => `Bonjour ${sender(message)},\n\nMerci pour votre message. Nous allons examiner votre demande et vous revenir rapidement.\n\nAu plaisir,\nGeneviève Côté`;
  async function analyze() { const r = root(); if (!r || state.loading) return; if (!state.inbox.length) await loadMailbox(); const done = processed(); const candidates = state.inbox.filter(m => senderEmail(m) && !done.includes(m.id)).slice(0, 5); if (!candidates.length) { feedback('À jour — aucun nouveau courriel à préparer.'); return; } const button = r.querySelector('[data-mail="analyze"]'); if (button) { button.disabled = true; button.textContent = 'Analyse…'; } let created = 0; for (const m of candidates) { try { await graph(`/me/messages/${encodeURIComponent(m.id)}/createReply`, { method:'POST', body:JSON.stringify({ comment:replyText(m)}) }); done.push(m.id); created++; } catch {} } saveProcessed(done); await loadMailbox(); feedback(`${created} brouillon${created > 1 ? 's' : ''} créé${created > 1 ? 's' : ''} dans Outlook.`); if (button) { button.disabled = false; button.textContent = 'Analyser maintenant'; } }
  async function createReply(form) { const m = state.selected || state.inbox[0]; const body = new FormData(form).get('reply'); if (!m || !body) return; const button = form.querySelector('button'); button.disabled = true; button.textContent = 'Création…'; try { await graph(`/me/messages/${encodeURIComponent(m.id)}/createReply`, { method:'POST', body:JSON.stringify({ comment:String(body)}) }); feedback('Réponse créée dans les brouillons Outlook. Rien n’a été envoyé.'); await loadMailbox(); state.view = 'drafts'; renderContent(); } catch (e) { feedback(e.message || 'Création du brouillon impossible.', true); button.disabled = false; button.textContent = 'Créer le brouillon de réponse'; } }
  async function createNew(form) { const data = Object.fromEntries(new FormData(form).entries()); const button = form.querySelector('button'); button.disabled = true; button.textContent = 'Création…'; try { await graph('/me/messages', { method:'POST', body:JSON.stringify({subject:data.subject || 'Suivi de votre dossier',body:{contentType:'Text',content:data.body},toRecipients:[{emailAddress:{address:data.to}}]}) }); feedback('Nouveau courriel créé dans les brouillons Outlook. Rien n’a été envoyé.'); form.reset(); await loadMailbox(); state.view = 'drafts'; renderContent(); } catch (e) { feedback(e.message || 'Création du brouillon impossible.', true); button.disabled = false; button.textContent = 'Créer dans Outlook'; } }
  function mount() { const old = document.querySelector('.inbox'); if (!old || old.closest('[data-mailbox-root]')) return; const card = old.closest('.card'); if (!card) return; card.innerHTML = shell(); renderContent(); setTimeout(() => { loadMailbox().then(() => analyze()).catch(() => undefined); }, 250); if (!window.__gcOutlookTimer) window.__gcOutlookTimer = setInterval(() => { if (root() && document.visibilityState === 'visible') loadMailbox().then(() => analyze()).catch(() => undefined); }, 5 * 60 * 1000); }
  document.addEventListener('click', e => { const a = e.target.closest('[data-mail]'); if (!a) return; const action = a.dataset.mail; if (action === 'refresh') loadMailbox(); if (action === 'analyze') analyze(); if (action === 'tab') { state.view = a.dataset.view; renderContent(); if (state.view === 'inbox' && !state.inbox.length) loadMailbox(); } if (action === 'open') { state.selected = state.inbox.find(m => m.id === a.dataset.id) || null; state.view = 'inbox'; renderContent(); } });
  document.addEventListener('submit', e => { if (e.target.matches('form[data-mail="reply"]')) { e.preventDefault(); createReply(e.target); } if (e.target.matches('form[data-mail="new"]')) { e.preventDefault(); createNew(e.target); } });
  new MutationObserver(mount).observe(document.body, { childList:true, subtree:true }); mount();
})();
