/* Microsoft Entra ID + Graph pour une SPA. Flux recommandé: Authorization Code + PKCE. */
window.M365={
  clientId:window.M365_CONFIG?.clientId||'eeff2f4a-7f6b-44fb-a33e-8d9990ce16e1',authority:window.M365_CONFIG?.authority||'https://login.microsoftonline.com/common',scopes:['User.Read','Mail.ReadWrite','Mail.Send','Calendars.ReadWrite'],instance:null,account:null,ready:false,loggingIn:false,
  async init(){if(this.ready)return this.instance;if(!window.msal)return null;this.instance=new msal.PublicClientApplication({auth:{clientId:this.clientId,authority:this.authority,redirectUri:window.location.origin+window.location.pathname,postLogoutRedirectUri:window.location.origin+window.location.pathname,navigateToLoginRequestUrl:false},cache:{cacheLocation:'localStorage',storeAuthStateInCookie:false}});await this.instance.initialize();const response=await this.instance.handleRedirectPromise();if(response?.account){this.account=response.account;this.instance.setActiveAccount(this.account);localStorage.setItem('m365-account',JSON.stringify({name:this.account.name,username:this.account.username}))}else{const accounts=this.instance.getAllAccounts();this.account=this.instance.getActiveAccount()||accounts[0]||null;if(this.account)this.instance.setActiveAccount(this.account)}this.ready=true;return this.instance},
  isConnected(){return Boolean(this.account||localStorage.getItem('m365-account'))},
  async connect(){if(location.protocol==='file:')throw new Error('Publiez le site en HTTPS avant de connecter Microsoft 365.');if(this.loggingIn)return;this.loggingIn=true;const c=await this.init();if(!c)throw new Error('Microsoft Entra ne se charge pas. Vérifiez que la page est publiée en HTTPS.');await c.loginRedirect({scopes:this.scopes,redirectUri:location.origin+location.pathname})},
  async login(){return this.connect()},
  async token(){const c=await this.init();if(!c||!this.account)throw new Error('Connectez d’abord votre compte Microsoft 365.');try{return(await c.acquireTokenSilent({account:this.account,scopes:this.scopes})).accessToken}catch{return(await c.acquireTokenRedirect({account:this.account,scopes:this.scopes}))}},
  async graph(path,options={}){const token=await this.token(),r=await fetch('https://graph.microsoft.com/v1.0'+path,{...options,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(`Microsoft Graph a retourné ${r.status}.`);return r.status===204?true:r.json()},
  async profile(){return this.graph('/me?$select=displayName,mail,userPrincipalName')},async messages(){const d=await this.graph('/me/mailFolders/inbox/messages?$top=25&$orderby=receivedDateTime desc&$select=id,subject,from,receivedDateTime,isRead,bodyPreview');return d.value||[]},async message(id){return this.graph('/me/messages/'+encodeURIComponent(id)+'?$select=id,subject,from,receivedDateTime,body,bodyPreview')},async createDraft({to,subject,body}){return this.graph('/me/messages',{method:'POST',body:JSON.stringify({subject,body:{contentType:'Text',content:body},toRecipients:[{emailAddress:{address:to}}]})})},async sendMessage({to,subject,body}){return this.graph('/me/sendMail',{method:'POST',body:JSON.stringify({message:{subject,body:{contentType:'Text',content:body},toRecipients:[{emailAddress:{address:to}}]},saveToSentItems:true})})},async disconnect(){if(this.instance)await this.instance.logoutRedirect({postLogoutRedirectUri:location.origin+location.pathname});this.account=null;localStorage.removeItem('m365-account')}
};
