/* Microsoft 365 / Outlook connection, based on the same MSAL + Graph flow used in Cuisine Concept. */
window.M365={
  clientId:'eeff2f4a-7f6b-44fb-a33e-8d9990ce16e1',authority:'https://login.microsoftonline.com/common',scopes:['User.Read','Mail.ReadWrite'],instance:null,account:null,
  async init(){if(!window.msal)return null;if(this.instance)return this.instance;this.instance=new msal.PublicClientApplication({auth:{clientId:this.clientId,authority:this.authority,redirectUri:window.location.href.split('?')[0],navigateToLoginRequestUrl:false},cache:{cacheLocation:'localStorage'}});await this.instance.initialize();this.account=this.instance.getActiveAccount()||this.instance.getAllAccounts()[0]||null;if(this.account)this.instance.setActiveAccount(this.account);return this.instance},
  async connect(){if(window.location.protocol==='file:')throw new Error('Le site doit être publié en HTTPS ou lancé sur localhost pour connecter Microsoft 365.');const c=await this.init();const r=await c.loginPopup({scopes:this.scopes,prompt:'select_account'});this.account=r.account;c.setActiveAccount(this.account);localStorage.setItem('m365-connected','1');return this.account},
  async token(){const c=await this.init();if(!this.account)throw new Error('Connectez d’abord votre compte Microsoft 365.');try{return(await c.acquireTokenSilent({account:this.account,scopes:this.scopes})).accessToken}catch(e){const r=await c.acquireTokenPopup({scopes:this.scopes});return r.accessToken}},
  async profile(){const t=await this.token();const r=await fetch('https://graph.microsoft.com/v1.0/me?$select=displayName,mail,userPrincipalName',{headers:{Authorization:'Bearer '+t}});if(!r.ok)throw new Error('Microsoft Graph a refusé la lecture du profil.');return r.json()},
  async messages(){const t=await this.token();const r=await fetch('https://graph.microsoft.com/v1.0/me/messages?$top=10&$select=subject,from,receivedDateTime,isRead',{headers:{Authorization:'Bearer '+t}});if(!r.ok)throw new Error('Impossible de lire les courriels Microsoft 365.');return (await r.json()).value||[]},
  async disconnect(){if(this.instance)await this.instance.clearCache();this.account=null;localStorage.removeItem('m365-connected')}
};
